#NOTE: This just needs to be set to a value bigger than the tile size
PL_MAX_DISPLACEMENT_X: 1000
PL_MAX_DISPLACEMENT_Y: 1000

SYNTH_STRATEGY: "AREA 2"

FP_SIZING: "absolute"

DESIGN_REPAIR_BUFFER_INPUT_PORTS: False
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: False

PL_TIMING_DRIVEN: False

CLOCK_PERIOD: 20.0
CLOCK_PORT: "UserCLK"

GRT_ANTENNA_REPAIR_ITERS: 10
GRT_ALLOW_CONGESTION: True

DRT_ANTENNA_REPAIR_ITERS: 10

PDN_MULTILAYER: False

BOTTOM_MARGIN_MULT: 1
TOP_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

DIODE_ON_PORTS: "both"

pdk::sky130A:
  #Floor planning
  IO_PIN_H_LAYER: "met3"
  IO_PIN_V_LAYER: "met2"

  # Routing
  RT_MAX_LAYER: met4

  # PDN
  PDN_VSPACING: 3.7
  PDN_VPITCH: 30
  PDN_VOFFSET: 5

  PDN_HSPACING: 3.7
  PDN_HPITCH: 30
  PDN_HOFFSET: 5

pdk::ihp-sg13g2:
  # Routing
  RT_MAX_LAYER: TopMetal1

  DIODE_CELL: "sg13g2_antennanp/A"

pdk::gf180mcuD:
  # Routing
  RT_MAX_LAYER: Metal4

  # PDN
  PDN_VPITCH: 100

  SYNTH_LATCH_MAP: "dir::../../../include/gf180mcuD_latchmap.v"
